steps:
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - -f
      - docker/random_forest/Dockerfile
      - -t
      - us-central1-docker.pkg.dev/fwa-mlops-accelerator-demo/fwa-mlops/random-forest-training:v1
      - .

images:
  - us-central1-docker.pkg.dev/fwa-mlops-accelerator-demo/fwa-mlops/random-forest-training:v1
